@startuml API Gateway

class PreprocessingResult{
    -openAPIDocument: JSON
    -resources: List<String>
    -tokens: List<String>
}

class ProcessingResult{
    -url: String
    -method: String
    -queryParams: List<(String, String)>
    -body:  String
}

class SendRequestService{
    +sendRequest(String path, List<(String, String)> params, String body): JSON
}

class TransationService{
    -sendRequestService: SendRequestService
    +translateNaturalLanguage(String nlpSentence, String language) : String
}

class PreprocessingService{
    -sendRequestService: SendRequestService
    +preprocessData(String url, String translatedNLPSentence) : PreprocessingResult
}

class NLPService{
    -sendRequestService: SendRequestService
    +processNLP(PreprocessingResult data): ProcessingResult
}

class GatewayOrchestrator {
    -transationService: TranslationService
    -preprocessingService: PreprocessingService
    -nlpService : NLPService 
    +preprocessNaturalLanguage(String url, String nlpSentence) : JSON 
}

class GatewayFunction {
	-gatewayOrchestrator : GatewayOrchestrator
	+preprocessNaturalLanguage (HttpRequest request) : HttpResponse
}
GatewayFunction --> GatewayOrchestrator
GatewayOrchestrator --> TransationService
GatewayOrchestrator --> PreprocessingService
GatewayOrchestrator --> NLPService
NLPService --> SendRequestService
TransationService --> SendRequestService
PreprocessingService --> SendRequestService
PreprocessingService -- PreprocessingResult
NLPService -- ProcessingResult

@enduml